Task 1: Create a 1D array of numbers from 0 to 9

In [5]:
import numpy as np
array = np.arange(0,10)
print(array)

[0 1 2 3 4 5 6 7 8 9]


Task 2: Create a 3 x 3 numpy array of all boolean 'Trues'

In [15]:
#As the integer 1 == bool value 'True' in Python:
bools = np.ones(9, dtype=bool)
all_bools = bools.reshape(3,3)
print(all_bools)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


Task 3: Extract all odd numbers from an array of 1 to 10

In [84]:
#plain Python solution using a for loop: 

#array = np.arange(0,11)
#no_odds_array = []
#for i in range(len(array)):
    #if i % 2 == 0 and i > 0:#
        #no_odds_array.append(i)
#print(no_odds_array)


#numpy solution: 

arr = np.arange(0,11)
#using array indexing:
new_arr = arr[arr % 2 == 1]
print(new_arr)     

[1 3 5 7 9]


Task 4: Replace all odd numbers in an array of 1 to 10 with the value -1

In [95]:
arr = np.arange(0,11)
#using array indexing:
arr[arr % 2 == 1] = -1
print(arr)


[ 0 -1  2 -1  4 -1  6 -1  8 -1 10]


Task 5: Convert a 1D array to a 2D array with two rows

In [102]:
new_arr = np.ones(8)
print(new_arr)
two_rows = new_arr.reshape(2,4)
print(two_rows)

[1. 1. 1. 1. 1. 1. 1. 1.]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


Task 6: Create two arrays, stack them vertically and calculate totals

In [167]:
a = np.arange(20,29).reshape(3,3)
b = np.arange(10,19).reshape(3,3)
print("This is a: \n", a)
print("This is b: \n", b)
stacked = np.vstack((a,b))
c = np.dot(a,b)
print("This is the matrix product c: \n", c)
d = np.sum(c)
print("This is the sum of all elements in matrix c:", d)


This is a: 
 [[20 21 22]
 [23 24 25]
 [26 27 28]]
This is b: 
 [[10 11 12]
 [13 14 15]
 [16 17 18]]
This is the matrix product c: 
 [[ 825  888  951]
 [ 942 1014 1086]
 [1059 1140 1221]]
This is the sum of all elements in matrix c: 9126


Extension Task 1: Create the specified pattern using only numpy functions

In [227]:
arr1 = np.array([1, 2, 3])

final = np.ones(3)
final = np.append(final, np.add(final, 1))
final = np.append(final, np.add(final, 1))
final = np.append(final, arr1)
final = np.append(final, arr1)
final = np.append(final, arr1)

print(final)


[1. 1. 1. 2. 2. 2. 2. 2. 2. 3. 3. 3. 1. 2. 3. 1. 2. 3. 1. 2. 3.]


Extension Task 2: In two arrays, remove all repeating items present in the second array

In [177]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([4, 5, 6, 7, 8, 9])
#Finding the duplicates by merging the two sets
duplicates = set(a) & set(b)
#Converting array b to list for list methods:
b = b.tolist()
#Looping through the list and removing the duplicates:
for i in duplicates:
    b.remove(i)
#Converting it back to array form:
b = np.array(b)
print(a)
print(b)

[1 2 3 4 5]
[6 7 8 9]


Extension Task 3: Get all items between 3 and 7 from a and b and sum them.

In [215]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([6, 7, 8, 9])

new_a = a[(a > 3) & (a < 7)]
print(new_a)
new_b = b[(b > 3) & (b < 7)]
print(new_b)
sum = np.add(new_a, new_b)
print(sum)

[4 5]
[6]
[10 11]
